### ISSUE TITLE
Trying to build the project in Visual Studio 2019 results with a build error.

### ISSUE THREAD

**Issue by Donaut** [sbarisic/NuklearDotNet#12]
First, it wants to update to the latest Windows SDK. ( I need to do that otherwise I have to install visual studio 2017 ). Result with a missing file called nuklear.h.
![image](https://user-images.githubusercontent.com/30203762/73599831-7c160080-4548-11ea-83f5-893efa19a50f.png)

**Comment by sbarisic** [comment]
Did you also clone the submodules?

**Comment by Donaut** [comment]
Thank you so much. It's working again :)
