### ISSUE TITLE
MonoGame implementation.

### ISSUE THREAD

**Issue by Donaut** [sbarisic/NuklearDotNet#14]
Hi!
Currently, I'm making an implementation for MonoGame. It's almost done but there is something wrong with the result. The texture corners don't have a strong line as in your SFML example. Also, the fonts have a little right shadow so they look blurred.

Any idea whats cause it?

![image](https://user-images.githubusercontent.com/30203762/91615150-3c4eb480-e983-11ea-85a9-83ec52181887.png)

**Comment by sbarisic** [comment]
What kind of texture filtering do you use? It should be point, not linear, and mipmaps should be disabled.

**Comment by Donaut** [comment]
Ok, the biggest problem was the Blending state. I think Nuklear uses premultiplied alpha while MonoGame didn't.

**Comment by Donaut** [comment]
Somehow I managed to solve the problem. If somebody has the knowledge why it's working please tell me.

**Comment by kriskeillor** [comment]
Can you share your process of getting NuklearDotNet to work in MonoGame? I just cloned the repo and I can't even get the examples to build. Not sure how to start with MonoGame.

The errors when I try to build ExampleShared or Example_WindowsForms:

```
Severity	Code	Description	File	Line	Suppression State
Error	C1083	Cannot open include file: 'nuklear.h': No such file or directory	C:\Dev\XNA--Monogame\NuklearDotNet\NuklearDotNetRepo\Nuklear2\Nuklear.c	17	
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	C:\Dev\XNA--Monogame\NuklearDotNet\NuklearDotNetRepo\ExampleShared\CSC	1	N/A
```

**Comment by sbarisic** [comment]
@kriskeillor please check the new issue i opened about this
