### ISSUE TITLE
[BUG] Force redraw will not occur if you don't have any input.

### ISSUE THREAD

**Issue by Donaut** [sbarisic/NuklearDotNet#19]
Calling ForceUpdate or NuklearAPI.QueueForceUpdate functions will do not run until you provide some input. (mouse move or a keypress).

Reproduce the issue in the SFML example.
1. **First, comment out all the input codes.**
![image](https://user-images.githubusercontent.com/30203762/91768459-e9bd0480-ebdd-11ea-8714-ff83092a9127.png)

2. **Inside the while loop use the _**NuklearAPI.QueueForceUpdate()**_ function.**

2. **Start Debugging and you will see that the IframeBuffered.BeginBuffer operation gets called 2-3 times and never again**

**Comment by Donaut** [comment]
Yes i read your previous post. But can't we do something about it?

**Comment by sbarisic** [comment]
Ah, yes, i see. I will try to fix it today. The problem is that i'm using direct memory compare with the buffer objects here
https://github.com/sbarisic/NuklearDotNet/blob/master/NuklearDotNet/NuklearAPI.cs#L167

**Comment by Donaut** [comment]
You don't need to do :D. Input event occur so often it's just not worth the pain.
