### ISSUE TITLE
Is this updated with recent Nuklear version?

### ISSUE THREAD

**Issue by nyaruku** [sbarisic/NuklearDotNet#25]
just asking

**Comment by sbarisic** [comment]
Not for a while. I'll bring it up to date sometime until the end of this year, probably even sooner.

**Comment by shayded-exe** [comment]
Just found this project now that I've ditched Unity and would love to see it updated!

**Comment by shayded-exe** [comment]
I'm going to try my hand at making a new auto-gen version of this with https://github.com/bottlenoselabs/c2cs

**Comment by sbarisic** [comment]
Added a new submodule which references the new github repository and compiled it, it seems to work. I am most likely missing some new functions they added in the last 3 years. If you notice any, please make a list and i'll implement these first.
