### ISSUE TITLE
How do I get the NuklearDevice?

### ISSUE THREAD

**Issue by NotHunter101** [sbarisic/NuklearDotNet#7]
I don't know how to find this for the Init method.

**Comment by sbarisic** [comment]
You are supposed to create your own class which inherits from NuklearDevice, this is made this way so you can use any renderer that you like. OpenGL, DirectX, SFML... whatever.

Here's an example one for SFML
https://github.com/sbarisic/NuklearDotNet/blob/master/Example_SFML/Program.cs#L19-L101

And then you just create an instance of it and pass it to Init

```csharp
SFMLDevice Dev = new SFMLDevice(SFML_RenderWindow);
NuklearAPI.Init(Dev);
```
