### ISSUE TITLE
I've pulled the repo and not a single example works

### ISSUE THREAD

**Issue by yar1k0v** [sbarisic/NuklearDotNet#8]
Is there any working example with all the ported components? Thanks.

**Comment by sbarisic** [comment]
There should be working examples before i updated the submodule, this should be the last commit that works
https://github.com/sbarisic/NuklearDotNet/commit/80875aaa53bcf529998305eb2d3b236eac214a4e

I'll look into it why the latest doesn't work.

**Comment by sbarisic** [comment]
Okay i found the source of the problem. In latest commit SFML example should work.
